class chordTable{
    constructor(){
        //lookup table for chords
        //first column contains chord names 
        //while the rest of the row contains the notes needed to make up that chord
        this.lookupTable = [
            //major
            ["C", "C", "E", "G"],
            ["C#", "C#", "F", "G#"],
            ["D", "D", "F#", "A"],
            ["D#", "D#", "G", "A#"],
            ["E", "E", "G#", "B"],
            ["F", "F", "A", "C"],
            ["F#", "F#", "A#", "C#"],
            ["G", "G", "B", "D"],
            ["G#", "G#", "C", "D#"],        
            ["A", "A", "C#", "E"],
            ["A#", "A#", "D", "F"],
            ["B", "B", "D#", "F#"],
            //minor
            ["Cm", "C", "D#", "G"],
            ["C#m", "C#", "E", "G#"],
            ["Dm", "D", "F", "A"],
            ["D#m", "D#", "F#", "A#"],
            ["Em", "E", "G", "B"],
            ["Fm", "F", "G#", "C"],
            ["F#m", "F#", "A", "C#"],
            ["Gm", "G", "A#", "D"],
            ["G#m", "G#", "B", "D#"],        
            ["Am", "A", "C", "E"],
            ["A#m", "A#", "C#", "F"],
            ["Bm", "B", "D", "F#"],
            //major 7th
            ["C7", "C", "E", "G", "A#"],
            ["C#7", "C#", "F", "G#", "B"],
            ["D7", "D", "F#", "A", "C"],
            ["D#7", "D#", "G", "A#", "C#"],
            ["E7", "E", "G#", "B", "D"],
            ["F7", "F", "A", "C", "D#"],
            ["F#7", "F#", "A#", "C#", "E"],
            ["G7", "G", "B", "D", "F"],
            ["G#7", "G#", "C", "D#", "F#"],        
            ["A7", "A", "C#", "E", "G"],
            ["A#7", "A#", "D", "F", "G#"],
            ["B7", "B", "D#", "F#", "A"],
            //minor 7th
            ["Cm7", "C", "D#", "G", "A#"],
            ["C#m7", "C#", "E", "G#", "B"],
            ["Dm7", "D", "F", "A", "C"],
            ["D#m7", "D#", "F#", "A#", "C#"],
            ["Em7", "E", "G", "B", "D"],
            ["Fm7", "F", "G#", "C", "D#"],
            ["F#m7", "F#", "A", "C#", "E"],
            ["Gm7", "G", "A#", "D", "F"],
            ["G#m7", "G#", "B", "D#", "F#"],        
            ["Am7", "A", "C", "E", "G"],
            ["A#m7", "A#", "C#", "F", "G#"],
            ["Bm7", "B", "D", "F#", "A"],
            //diminished
            ["Cdim", "C", "D#", "F#"],
            ["C#dim", "C#", "E", "G"],
            ["Ddim", "D", "F", "G#"],
            ["D#dim", "D#", "F#", "A"],
            ["Edim", "E", "G", "A#"],
            ["Fdim", "F", "G#", "B"],
            ["F#dim", "F#", "A", "C"],
            ["Gdim", "G", "A#", "C#"],
            ["G#dim", "G#", "B", "D"],        
            ["Adim", "A", "C", "D#"],
            ["A#dim", "A#", "C#", "E"],
            ["Bdim", "B", "D", "F"],
            //augmented
            ["Caug", "C", "E", "G#"],
            ["C#aug", "C#", "F", "A"],
            ["Daug", "D", "F#", "A#"],
            ["D#aug", "D#", "G", "B"],
            ["Eaug", "E", "G#", "C"],
            ["Faug", "F", "A", "C#"],
            ["F#aug", "F#", "A#", "D"],
            ["Gaug", "G", "B", "D#"],
            ["G#aug", "G#", "C", "E"],        
            ["Aaug", "A", "C#", "F"],
            ["A#aug", "A#", "D", "F#"],
            ["Baug", "B", "D#", "G"],
            //sus2
            ["Csus2", "C", "D", "G"],
            ["C#sus2", "C#", "D#", "G#"],
            ["Dsus2", "D", "E", "A"],
            ["D#sus2", "D#", "F", "A#"],
            ["Esus2", "E", "F#", "B"],
            ["Fsus2", "F", "G", "C"],
            ["F#sus2", "F#", "G#", "C#"],
            ["Gsus2", "G", "A", "D"],
            ["G#sus2", "G#", "A#", "D#"],        
            ["Asus2", "A", "B", "E"],
            ["A#sus2", "A#", "C", "F"],
            ["Bsus2", "B", "C#", "F#"],
            //sus4
            ["Csus4", "C", "F", "G"],
            ["C#sus4", "C#", "F#", "G#"],
            ["Dsus4", "D", "G", "A"],
            ["D#sus4", "D#", "G#", "A#"],
            ["Esus4", "E", "A", "B"],
            ["Fsus4", "F", "A#", "C"],
            ["F#sus4", "F#", "B", "C#"],
            ["Gsus4", "G", "C", "D"],
            ["G#sus4", "G#", "C#", "D#"],        
            ["Asus4", "A", "D", "E"],
            ["A#sus4", "A#", "D#", "F"],
            ["Bsus4", "B", "E", "F#"],
        ]
        return this.lookupTable;
    }
}